# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-07 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedUser',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='EmailRevifyRecord',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_classname',
        ),
    ]
